import { useState, useEffect } from "react";
import { BrowserRouter as Router, Route, Routes } from "react-router-dom";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Tasks from "./components/Tasks";
import AddTask from "./components/AddTask";
import About from "./components/About";

function App() {
  const [showAddTask, setShowAddTask] = useState(false); // state to show/hide AddTask form
  const [tasks, setTasks] = useState([]); // state to hold tasks array

  // Get Tasks from server
  useEffect(() => {
    const getTasks = async () => {
      const tasksFromServer = await fetchTasks();
      setTasks(tasksFromServer); // adds tp our tasks state
    }

    getTasks();
  }, []); //empty dependency array means it runs if only on initial render

  // Fetch Tasks
      //fetch returns a promise
  const fetchTasks = async () => { //await promise/response from server
    const result = await fetch('http://localhost:5002/tasks'); //fetch tasks from json server 
    const data = await result.json(); //await data from response in json format

    return data;
  };

  // Fetch Task
  const fetchTask = async (id) => { //await promise/response from server
    const result = await fetch(`http://localhost:5002/tasks/${id}`); //fetch task from json server using backticks to insert id
    const data = await result.json(); //await data from response in json format

    return data;
  };
  // Add Task
  const addTask = async (task) => {
    const result = await fetch('http://localhost:5002/tasks', {
      method: 'POST',
      // since adding data, need to specify headers and body to specify type of data being sent
      headers: {
        'Content-type': 'application/json',
      },
      body: JSON.stringify(task), //convert javascript task object to json string
    })

    // data returned is the new task added including the id generated by json server
    const data = await result.json(); //await data from response in json format
    
    setTasks([...tasks, data]); // add new task to tasks array
  };

  //Delete Task
  const deleteTask = async (id) => {
    await fetch(`http://localhost:5002/tasks/${id}`, { // dont need tp save in a variable since not getting any data back
      method: 'DELETE',
    });

    setTasks(tasks.filter((task) => task.id !== id)); //filter out deleted task from UI
  };

  // Toggle Reminder
  const toggleReminder = async (id) => {
    const taskToToggle = await fetchTask(id); //get the task to toggle
    const updatedTask = { ...taskToToggle, reminder: !taskToToggle.reminder }; //create updated task with toggled reminder

    const result = await fetch(`http://localhost:5002/tasks/${id}`, {
      method: 'PUT',
      headers: {
        'Content-type': 'application/json',
      },
      body: JSON.stringify(updatedTask),
    });

    const data = await result.json();

    //map through tasks, find the one with the matching id, and toggle its reminder property
    setTasks(tasks.map((task) =>
      task.id === id ? { ...task, reminder: data.reminder } : task
    ));
  };

  return (
    <Router>
    <div className="container">
      {/* pass onAdd prop to Header to toggle showAddTask state */}
      <Header onAdd={() => setShowAddTask(!showAddTask)} showAdd={showAddTask} />
      <Routes>
      <Route path='/' element={
        <>
          {/* addtask is dependent on showAddTask state */}
          {showAddTask && <AddTask onAdd={addTask} />}
          {/*if tasks exist, render Tasks component, else show message*/}
          {tasks.length > 0 ? (<Tasks tasks={tasks} onDelete={deleteTask} onToggle={toggleReminder} />) : ('No Tasks to Show')}
        </>
       } />
      <Route path='/about' element={<About />} />
      </Routes>
      <Footer /> 
    </div>
    </Router>
  );
}

export default App;
